name: Github CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Starting build process
        run: echo "Starting build process..."

      - name: Build success
        run: echo "Project is building successfully!"